# .graphclientrc.yml
cache:
  file:
    path: ./.graphclient-cache.json
sources:
  - name: fabrica-ethereum
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/0f3e6e7bbd04/fabrica/fabrica-noipfs-ethereum/version/v0.0.8/api
    transforms:
      - autoPagination:
          validateSchema: true # Validates that the schema source actually contains the required input filters.
          limitOfRecords: 1000 # Default is 1000, you can change if your indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.
      - prefix:
          includeRootOperations: true
          includeTypes: false
          mode: bare | wrap
          value: ethereum_
      - typeMerging:
  - name: fabrica-sepolia
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/0f3e6e7bbd04/fabrica/fabrica-noipfs-sepolia/version/v0.0.19/api
    transforms:
      - autoPagination:
          validateSchema: true # Validates that the schema source actually contains the required input filters.
          limitOfRecords: 1000 # Default is 1000, you can change if your indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.
      - prefix:
          includeRootOperations: true
          includeTypes: false
          mode: bare | wrap
          value: sepolia_
      - typeMerging:
