envVarGroups:
  - name: loan-offer-bot
    envVars:
      # No code should directly reference this, except for reporting purposes (e.g. logging) and cache keys
      #  (since every release stage shares a cache, and sometimes you want to cache things separately per
      #  release stage, e.g. to track if an email was sent). Instead, env vars should be created for each
      #  separate configurable option, so they can be changed independent of the environment
      - key: NODE_ENV
        value: production

services:
  - type: worker
    name: loan-offer-bot
    runtime: node
    region: oregon
    repo: https://github.com/fabrica-land/loan-offer-bot
    branch: main
    buildCommand: 'yarn && yarn build'
    startCommand: 'yarn start'
    autoDeploy: true
    envVars:
      - fromGroup: loan-offer-bot
